# Generated by Django 2.0 on 2020-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEACH_EDISONapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DOB',
            field=models.CharField(blank=True, max_length=17, verbose_name='Date Of Birth'),
        ),
    ]
