# Generated by Django 2.0 on 2020-04-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEACH_EDISONapp', '0002_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
